Project Recipient Application/Controllers/AcountController.cs
using CaptchaMvc.HtmlHelpers;
using Project_Recipient_Application.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Project_Recipient_Application.Controllers
{
    public class AcountController : Controller
    {
        DatabaseContext db = new DatabaseContext();
        // GET: Acount
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(User user)
        {
            if (ModelState.IsValid)
            {
                if (this.IsCaptchaValid(""))
                {
                    string Hash = FormsAuthentication.HashPasswordForStoringInConfigFile(user.Password, "MD5");

                    var q = db.Useres.FirstOrDefault(u => u.Username == user.Username && u.Password == Hash);

                    if (q != null)
                    {
                        FormsAuthentication.SetAuthCookie(user.Username, true);

                        if (q.Activeate)
                        {
                            if (q.Role.RoleName == "admin"||q.Role.RoleName=="user")
                            {
                                return Redirect("/Admin/Dashboard/Index");
                            }
                            else
                            {
                                return RedirectToAction("Index", "Home");
                            }
                        }
                    }
                    else
                    {
                        ViewBag.Errorpass = "شماره تلفن همراه یا کلمه عبور شما اشتباه است";
                    }

                }
                else
                {
                    ViewBag.ErrMessage = "کد امنیتی اشتباه است";
                }
            }
            else
            {
                ModelState.AddModelError("UserPassword", "شماره تلفن همراه یا کلمه عبور شما اشتباه است");
            }

            return View();
        }
    }
}

Project Recipient Application/Views/Acount/Index.cshtml
@using CaptchaMvc.HtmlHelpers

@{
    Layout = null;
}

<html lang="fa">

<head>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <link href="~/Content/Acount/Style.css" rel="stylesheet" />
</head>

<body dir="rtl">
    <div class="coontainer">
        <div class="frame">
            <div class="lockpic">
                <img src="~/Images/shield.png" />
            </div>
            @using (Html.BeginForm("Index", "Acount"))
            {
                <div class="formpanel">
                    <h2>نام کاربری :</h2>
                    <input type="text" name="username" />
                    <p style="font-size:14px; display:block;color:red; margin-top:8px;">@ViewBag.Errorpass</p>
                    <h2> گذرواژه :</h2>
                    <input type="password" name="password" />
                    <h2> کد امنیتی :</h2>
                    @Html.MathCaptcha("", "", "کد امنیتی را وارد کنید", true)
                    <br />
                    <p style="font-size:14px; display:block;color:red; margin-top:-25px;">@ViewBag.ErrMessage</p>
                    <button type="submit">ورود</button>
                </div>
            }
        </div>
    </div>

</body>

</html>